kind: pipeline
name: default

steps:
- name: discuz
  image: docker:git
  commands:
  - git clone -b master https://gitee.com/ComsenzDiscuz/DiscuzX.git discuz

- name: publish
  image: plugins/docker
  settings:
    repo: v7lin/discuz
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
    - latest
    - 3.4
